#!/bin/bash

# PulseExpends Google OAuth Configuration Script
# This script helps you configure Google OAuth for authentication

echo "=============================================="
echo "  PulseExpends - Google OAuth Configuration   "
echo "=============================================="
echo ""

# Check if .env file exists
if [ ! -f "backend/auth/.env" ]; then
    echo "Creating .env file from template..."
    cp backend/auth/.env.example backend/auth/.env
    echo ".env file created. Please edit it with your configuration."
    echo ""
fi

echo "📋 Follow these steps to configure Google OAuth:"
echo ""
echo "1. Go to Google Cloud Console:"
echo "   https://console.cloud.google.com/"
echo ""
echo "2. Create a new project or select existing one"
echo ""
echo "3. Enable the Google+ API:"
echo "   - Go to 'APIs & Services' → 'Library'"
echo "   - Search for 'Google+ API'"
echo "   - Click 'Enable'"
echo ""
echo "4. Create OAuth 2.0 credentials:"
echo "   - Go to 'APIs & Services' → 'Credentials'"
echo "   - Click 'Create Credentials' → 'OAuth client ID'"
echo "   - Application type: 'Web application'"
echo ""
echo "5. Configure authorized redirect URIs:"
echo "   For development:"
echo "   - http://localhost:8082/api/auth/google/callback"
echo "   - http://localhost:3000/auth/callback"
echo ""
echo "   For production (replace with your domain):"
echo "   - http://pulseexpends.duckdns.org/api/auth/google/callback"
echo "   - http://pulseexpends.duckdns.org/auth/callback"
echo ""
echo "6. Configure authorized JavaScript origins:"
echo "   For development:"
echo "   - http://localhost:3000"
echo "   - http://localhost:8082"
echo ""
echo "   For production:"
echo "   - http://pulseexpends.duckdns.org"
echo "   - https://pulseexpends.duckdns.org"
echo ""
echo "7. After creating credentials, you'll get:"
echo "   - Client ID"
echo "   - Client Secret"
echo ""
echo "8. Update your .env file:"
echo "   GOOGLE_CLIENT_ID=your-client-id.apps.googleusercontent.com"
echo "   GOOGLE_CLIENT_SECRET=your-client-secret"
echo ""
echo "9. For production, also update:"
echo "   GOOGLE_REDIRECT_URL=http://pulseexpends.duckdns.org/api/auth/google/callback"
echo "   FRONTEND_URL=http://pulseexpends.duckdns.org"
echo "   COOKIE_SECURE=true"
echo "   COOKIE_DOMAIN=pulseexpends.duckdns.org"
echo ""
echo "10. Restart the auth server:"
echo "    sudo systemctl restart pulseexpends-auth-server"
echo ""
echo "📝 Notes:"
echo "- Make sure your domain is properly configured in DuckDNS"
echo "- For HTTPS, you need SSL certificates (Let's Encrypt)"
echo "- Test the OAuth flow in development first"
echo ""
echo "🔐 Security recommendations:"
echo "- Use strong JWT and cookie secrets in production"
echo "- Enable HTTPS in production"
echo "- Set appropriate CORS origins"
echo "- Use environment variables, not hardcoded values"
echo ""
echo "✅ Configuration complete when:"
echo "- You can register with email/password"
echo "- You can login with Google"
echo "- Sessions work across page reloads"
echo "- User data is persisted in database"
echo ""

# Check if running in ECS
if [ -f "/opt/PulseExpends/backend/auth/.env" ]; then
    echo "📦 ECS deployment detected!"
    echo ""
    echo "To configure Google OAuth on ECS:"
    echo "1. SSH into your ECS instance:"
    echo "   ssh -i pulse-expends-key.pem root@182.160.24.205"
    echo ""
    echo "2. Edit the environment file:"
    echo "   nano /opt/PulseExpends/backend/auth/.env"
    echo ""
    echo "3. Update Google OAuth credentials"
    echo ""
    echo "4. Restart the service:"
    echo "   sudo systemctl restart pulseexpends-auth-server"
    echo ""
    echo "5. Check logs:"
    echo "   sudo journalctl -u pulseexpends-auth-server -f"
fi

echo "=============================================="
echo "  Need help? Check the documentation:"
echo "  https://github.com/dssr1012/PulseExpends"
echo "=============================================="